// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type NotificationChannelInitParameters struct {

	// Name of the notification channel.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Slack notification configuration. At most one block.
	SlackConfigs []SlackConfigsInitParameters `json:"slackConfigs,omitempty" tf:"slack_configs,omitempty"`

	// Webhook notification configuration. At most one block.
	WebhookConfigs []WebhookConfigsInitParameters `json:"webhookConfigs,omitempty" tf:"webhook_configs,omitempty"`
}

type NotificationChannelObservation struct {

	// Creation time of the notification channel.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the notification channel.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Slack notification configuration. At most one block.
	SlackConfigs []SlackConfigsObservation `json:"slackConfigs,omitempty" tf:"slack_configs,omitempty"`

	// Type of the notification channel (derived from config block).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Last update time of the notification channel.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Webhook notification configuration. At most one block.
	WebhookConfigs []WebhookConfigsObservation `json:"webhookConfigs,omitempty" tf:"webhook_configs,omitempty"`
}

type NotificationChannelParameters struct {

	// Name of the notification channel.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Slack notification configuration. At most one block.
	// +kubebuilder:validation:Optional
	SlackConfigs []SlackConfigsParameters `json:"slackConfigs,omitempty" tf:"slack_configs,omitempty"`

	// Webhook notification configuration. At most one block.
	// +kubebuilder:validation:Optional
	WebhookConfigs []WebhookConfigsParameters `json:"webhookConfigs,omitempty" tf:"webhook_configs,omitempty"`
}

type SlackConfigsInitParameters struct {

	// Slack incoming webhook URL.
	APIURLSecretRef v1.LocalSecretKeySelector `json:"apiurlSecretRef" tf:"-"`

	// Slack channel to post to (e.g. #ops-alerts).
	Channel *string `json:"channel,omitempty" tf:"channel,omitempty"`

	// Slack icon emoji for the bot.
	IconEmoji *string `json:"iconEmoji,omitempty" tf:"icon_emoji,omitempty"`

	// Whether to send a notification when the alert resolves.
	SendResolved *bool `json:"sendResolved,omitempty" tf:"send_resolved,omitempty"`

	// Go template for the Slack message body.
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// Go template for the Slack message title.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// Slack username for the bot.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SlackConfigsObservation struct {

	// Slack channel to post to (e.g. #ops-alerts).
	Channel *string `json:"channel,omitempty" tf:"channel,omitempty"`

	// Slack icon emoji for the bot.
	IconEmoji *string `json:"iconEmoji,omitempty" tf:"icon_emoji,omitempty"`

	// Whether to send a notification when the alert resolves.
	SendResolved *bool `json:"sendResolved,omitempty" tf:"send_resolved,omitempty"`

	// Go template for the Slack message body.
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// Go template for the Slack message title.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// Slack username for the bot.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SlackConfigsParameters struct {

	// Slack incoming webhook URL.
	// +kubebuilder:validation:Optional
	APIURLSecretRef v1.LocalSecretKeySelector `json:"apiurlSecretRef" tf:"-"`

	// Slack channel to post to (e.g. #ops-alerts).
	// +kubebuilder:validation:Optional
	Channel *string `json:"channel,omitempty" tf:"channel,omitempty"`

	// Slack icon emoji for the bot.
	// +kubebuilder:validation:Optional
	IconEmoji *string `json:"iconEmoji,omitempty" tf:"icon_emoji,omitempty"`

	// Whether to send a notification when the alert resolves.
	// +kubebuilder:validation:Optional
	SendResolved *bool `json:"sendResolved,omitempty" tf:"send_resolved,omitempty"`

	// Go template for the Slack message body.
	// +kubebuilder:validation:Optional
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// Go template for the Slack message title.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// Slack username for the bot.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type WebhookConfigsInitParameters struct {

	// Whether to send a notification when the alert resolves.
	SendResolved *bool `json:"sendResolved,omitempty" tf:"send_resolved,omitempty"`

	// Webhook endpoint URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type WebhookConfigsObservation struct {

	// Whether to send a notification when the alert resolves.
	SendResolved *bool `json:"sendResolved,omitempty" tf:"send_resolved,omitempty"`

	// Webhook endpoint URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type WebhookConfigsParameters struct {

	// Whether to send a notification when the alert resolves.
	// +kubebuilder:validation:Optional
	SendResolved *bool `json:"sendResolved,omitempty" tf:"send_resolved,omitempty"`

	// Webhook endpoint URL.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

// NotificationChannelSpec defines the desired state of NotificationChannel
type NotificationChannelSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NotificationChannelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NotificationChannelInitParameters `json:"initProvider,omitempty"`
}

// NotificationChannelStatus defines the observed state of NotificationChannel.
type NotificationChannelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NotificationChannelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NotificationChannel is the Schema for the NotificationChannels API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,signoz}
type NotificationChannel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   NotificationChannelSpec   `json:"spec"`
	Status NotificationChannelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NotificationChannelList contains a list of NotificationChannels
type NotificationChannelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NotificationChannel `json:"items"`
}

// Repository type metadata.
var (
	NotificationChannel_Kind             = "NotificationChannel"
	NotificationChannel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NotificationChannel_Kind}.String()
	NotificationChannel_KindAPIVersion   = NotificationChannel_Kind + "." + CRDGroupVersion.String()
	NotificationChannel_GroupVersionKind = CRDGroupVersion.WithKind(NotificationChannel_Kind)
)

func init() {
	SchemeBuilder.Register(&NotificationChannel{}, &NotificationChannelList{})
}
