// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AlertInitParameters struct {

	// (String) Name of the alert.
	// Name of the alert.
	Alert *string `json:"alert,omitempty" tf:"alert,omitempty"`

	// (String) Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	AlertType *string `json:"alertType,omitempty" tf:"alert_type,omitempty"`

	// (Boolean) Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels. Deprecated: This field is no longer needed and will be ignored.
	// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
	BroadcastToAll *bool `json:"broadcastToAll,omitempty" tf:"broadcast_to_all,omitempty"`

	// (String) Condition of the alert.
	// Condition of the alert.
	Condition *string `json:"condition,omitempty" tf:"condition,omitempty"`

	// (String) Description of the alert.
	// Description of the alert.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the alert is disabled.
	// Whether the alert is disabled.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The evaluation window of the alert. By default, it is 5m0s.
	// The evaluation window of the alert. By default, it is 5m0s.
	EvalWindow *string `json:"evalWindow,omitempty" tf:"eval_window,omitempty"`

	// (String) Evaluation configuration of the alert as JSON. Only used when schema_version is v2 or higher.
	// Evaluation settings for the alert (JSON). Only used when schema_version is v2 or higher.
	Evaluation *string `json:"evaluation,omitempty" tf:"evaluation,omitempty"`

	// (String) The frequency of the alert. By default, it is 1m0s.
	// The frequency of the alert. By default, it is 1m0s.
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (Map of String) Labels of the alert. Severity is a required label.
	// Labels of the alert. Severity is a required label.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) Notification settings for the alert. Only used when schema_version is v2 or higher. (see below for nested schema)
	NotificationSettings *NotificationSettingsInitParameters `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (List of String) Preferred channels of the alert. By default, it is empty.
	// Preferred channels of the alert. By default, it is empty.
	PreferredChannels []*string `json:"preferredChannels,omitempty" tf:"preferred_channels,omitempty"`

	// (String) Type of the alert. Possible values are: threshold_rule and promql_rule.
	// Type of the alert. Possible values are: threshold_rule and promql_rule.
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// (String) Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notification_settings are supported.
	// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notification_settings are supported.
	SchemaVersion *string `json:"schemaVersion,omitempty" tf:"schema_version,omitempty"`

	// (String) Severity of the alert. Possible values are: info, warning, error, and critical.
	// Severity of the alert. Possible values are: info, warning, error, and critical.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// (String) Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) Summary of the alert.
	// Summary of the alert.
	Summary *string `json:"summary,omitempty" tf:"summary,omitempty"`

	// (String) Version of the alert. By default, it is v4.
	// Version of the alert. By default, it is v4.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AlertObservation struct {

	// (String) Name of the alert.
	// Name of the alert.
	Alert *string `json:"alert,omitempty" tf:"alert,omitempty"`

	// (String) Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	AlertType *string `json:"alertType,omitempty" tf:"alert_type,omitempty"`

	// (Boolean) Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels. Deprecated: This field is no longer needed and will be ignored.
	// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
	BroadcastToAll *bool `json:"broadcastToAll,omitempty" tf:"broadcast_to_all,omitempty"`

	// (String) Condition of the alert.
	// Condition of the alert.
	Condition *string `json:"condition,omitempty" tf:"condition,omitempty"`

	// (String) Creation time of the alert.
	// Creation time of the alert.
	CreateAt *string `json:"createAt,omitempty" tf:"create_at,omitempty"`

	// (String) Creator of the alert.
	// Creator of the alert.
	CreateBy *string `json:"createBy,omitempty" tf:"create_by,omitempty"`

	// (String) Description of the alert.
	// Description of the alert.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the alert is disabled.
	// Whether the alert is disabled.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The evaluation window of the alert. By default, it is 5m0s.
	// The evaluation window of the alert. By default, it is 5m0s.
	EvalWindow *string `json:"evalWindow,omitempty" tf:"eval_window,omitempty"`

	// (String) Evaluation configuration of the alert as JSON. Only used when schema_version is v2 or higher.
	// Evaluation settings for the alert (JSON). Only used when schema_version is v2 or higher.
	Evaluation *string `json:"evaluation,omitempty" tf:"evaluation,omitempty"`

	// (String) The frequency of the alert. By default, it is 1m0s.
	// The frequency of the alert. By default, it is 1m0s.
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (String) Autogenerated unique ID for the alert.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) Labels of the alert. Severity is a required label.
	// Labels of the alert. Severity is a required label.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) Notification settings for the alert. Only used when schema_version is v2 or higher. (see below for nested schema)
	NotificationSettings *NotificationSettingsObservation `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (List of String) Preferred channels of the alert. By default, it is empty.
	// Preferred channels of the alert. By default, it is empty.
	PreferredChannels []*string `json:"preferredChannels,omitempty" tf:"preferred_channels,omitempty"`

	// (String) Type of the alert. Possible values are: threshold_rule and promql_rule.
	// Type of the alert. Possible values are: threshold_rule and promql_rule.
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// (String) Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notification_settings are supported.
	// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notification_settings are supported.
	SchemaVersion *string `json:"schemaVersion,omitempty" tf:"schema_version,omitempty"`

	// (String) Severity of the alert. Possible values are: info, warning, error, and critical.
	// Severity of the alert. Possible values are: info, warning, error, and critical.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// (String) Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) State of the alert.
	// State of the alert.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Summary of the alert.
	// Summary of the alert.
	Summary *string `json:"summary,omitempty" tf:"summary,omitempty"`

	// (String) Last update time of the alert.
	// Last update time of the alert.
	UpdateAt *string `json:"updateAt,omitempty" tf:"update_at,omitempty"`

	// (String) Last updater of the alert.
	// Last updater of the alert.
	UpdateBy *string `json:"updateBy,omitempty" tf:"update_by,omitempty"`

	// (String) Version of the alert. By default, it is v4.
	// Version of the alert. By default, it is v4.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AlertParameters struct {

	// (String) Name of the alert.
	// Name of the alert.
	// +kubebuilder:validation:Optional
	Alert *string `json:"alert,omitempty" tf:"alert,omitempty"`

	// (String) Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	// Type of the alert. Possible values are: METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, and EXCEPTIONS_BASED_ALERT.
	// +kubebuilder:validation:Optional
	AlertType *string `json:"alertType,omitempty" tf:"alert_type,omitempty"`

	// (Boolean) Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels. Deprecated: This field is no longer needed and will be ignored.
	// Whether to broadcast the alert to all the alerting channels. By default, the alert is only sent to the preferred channels.
	// +kubebuilder:validation:Optional
	BroadcastToAll *bool `json:"broadcastToAll,omitempty" tf:"broadcast_to_all,omitempty"`

	// (String) Condition of the alert.
	// Condition of the alert.
	// +kubebuilder:validation:Optional
	Condition *string `json:"condition,omitempty" tf:"condition,omitempty"`

	// (String) Description of the alert.
	// Description of the alert.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the alert is disabled.
	// Whether the alert is disabled.
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The evaluation window of the alert. By default, it is 5m0s.
	// The evaluation window of the alert. By default, it is 5m0s.
	// +kubebuilder:validation:Optional
	EvalWindow *string `json:"evalWindow,omitempty" tf:"eval_window,omitempty"`

	// (String) Evaluation configuration of the alert as JSON. Only used when schema_version is v2 or higher.
	// Evaluation settings for the alert (JSON). Only used when schema_version is v2 or higher.
	// +kubebuilder:validation:Optional
	Evaluation *string `json:"evaluation,omitempty" tf:"evaluation,omitempty"`

	// (String) The frequency of the alert. By default, it is 1m0s.
	// The frequency of the alert. By default, it is 1m0s.
	// +kubebuilder:validation:Optional
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (Map of String) Labels of the alert. Severity is a required label.
	// Labels of the alert. Severity is a required label.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes) Notification settings for the alert. Only used when schema_version is v2 or higher. (see below for nested schema)
	// +kubebuilder:validation:Optional
	NotificationSettings *NotificationSettingsParameters `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (List of String) Preferred channels of the alert. By default, it is empty.
	// Preferred channels of the alert. By default, it is empty.
	// +kubebuilder:validation:Optional
	PreferredChannels []*string `json:"preferredChannels,omitempty" tf:"preferred_channels,omitempty"`

	// (String) Type of the alert. Possible values are: threshold_rule and promql_rule.
	// Type of the alert. Possible values are: threshold_rule and promql_rule.
	// +kubebuilder:validation:Optional
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// (String) Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notification_settings are supported.
	// Schema version of the alert. By default, it is v1. For v2+ schemas, additional fields like evaluation and notification_settings are supported.
	// +kubebuilder:validation:Optional
	SchemaVersion *string `json:"schemaVersion,omitempty" tf:"schema_version,omitempty"`

	// (String) Severity of the alert. Possible values are: info, warning, error, and critical.
	// Severity of the alert. Possible values are: info, warning, error, and critical.
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// (String) Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	// Source of the alert. By default, it is <SIGNOZ_ENDPOINT>/alerts.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) Summary of the alert.
	// Summary of the alert.
	// +kubebuilder:validation:Optional
	Summary *string `json:"summary,omitempty" tf:"summary,omitempty"`

	// (String) Version of the alert. By default, it is v4.
	// Version of the alert. By default, it is v4.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type NotificationSettingsInitParameters struct {

	// (List of String) List of labels to group notifications by, use 'all' to get different notification for each unique parameters.
	// Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
	GroupBy []*string `json:"groupBy,omitempty" tf:"group_by,omitempty"`

	// (Attributes) Renotify settings for the alert. (see below for nested schema)
	Renotify *RenotifyInitParameters `json:"renotify,omitempty" tf:"renotify,omitempty"`

	// (Boolean) Whether to use notification policy. By default, it is false.
	// Use policy in the alert. By default, it is false.
	UsePolicy *bool `json:"usePolicy,omitempty" tf:"use_policy,omitempty"`
}

type NotificationSettingsObservation struct {

	// (List of String) List of labels to group notifications by, use 'all' to get different notification for each unique parameters.
	// Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
	GroupBy []*string `json:"groupBy,omitempty" tf:"group_by,omitempty"`

	// (Attributes) Renotify settings for the alert. (see below for nested schema)
	Renotify *RenotifyObservation `json:"renotify,omitempty" tf:"renotify,omitempty"`

	// (Boolean) Whether to use notification policy. By default, it is false.
	// Use policy in the alert. By default, it is false.
	UsePolicy *bool `json:"usePolicy,omitempty" tf:"use_policy,omitempty"`
}

type NotificationSettingsParameters struct {

	// (List of String) List of labels to group notifications by, use 'all' to get different notification for each unique parameters.
	// Group by the alert. By default, it is empty, use '__all__' to get different notification for each unique parameters.
	// +kubebuilder:validation:Optional
	GroupBy []*string `json:"groupBy,omitempty" tf:"group_by,omitempty"`

	// (Attributes) Renotify settings for the alert. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Renotify *RenotifyParameters `json:"renotify,omitempty" tf:"renotify,omitempty"`

	// (Boolean) Whether to use notification policy. By default, it is false.
	// Use policy in the alert. By default, it is false.
	// +kubebuilder:validation:Optional
	UsePolicy *bool `json:"usePolicy,omitempty" tf:"use_policy,omitempty"`
}

type RenotifyInitParameters struct {

	// (List of String) List of alert states to trigger renotification. Possible values are: firing, nodata.
	// For which AlertStates of the alert want to get renotified.
	AlertStates []*string `json:"alertStates,omitempty" tf:"alert_states,omitempty"`

	// (Boolean) Whether renotify is enabled.
	// To enable the re-notification of the alert.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Renotification interval (e.g., "25m0s"). By default, it is empty.
	// Re-notify interval of the alert.
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`
}

type RenotifyObservation struct {

	// (List of String) List of alert states to trigger renotification. Possible values are: firing, nodata.
	// For which AlertStates of the alert want to get renotified.
	AlertStates []*string `json:"alertStates,omitempty" tf:"alert_states,omitempty"`

	// (Boolean) Whether renotify is enabled.
	// To enable the re-notification of the alert.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Renotification interval (e.g., "25m0s"). By default, it is empty.
	// Re-notify interval of the alert.
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`
}

type RenotifyParameters struct {

	// (List of String) List of alert states to trigger renotification. Possible values are: firing, nodata.
	// For which AlertStates of the alert want to get renotified.
	// +kubebuilder:validation:Optional
	AlertStates []*string `json:"alertStates" tf:"alert_states,omitempty"`

	// (Boolean) Whether renotify is enabled.
	// To enable the re-notification of the alert.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Renotification interval (e.g., "25m0s"). By default, it is empty.
	// Re-notify interval of the alert.
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval" tf:"interval,omitempty"`
}

// AlertSpec defines the desired state of Alert
type AlertSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AlertParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AlertInitParameters `json:"initProvider,omitempty"`
}

// AlertStatus defines the observed state of Alert.
type AlertStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AlertObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Alert is the Schema for the Alerts API. Creates and manages alert resources in SigNoz.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,signoz}
type Alert struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alert) || (has(self.initProvider) && has(self.initProvider.alert))",message="spec.forProvider.alert is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alertType) || (has(self.initProvider) && has(self.initProvider.alertType))",message="spec.forProvider.alertType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.condition) || (has(self.initProvider) && has(self.initProvider.condition))",message="spec.forProvider.condition is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.severity) || (has(self.initProvider) && has(self.initProvider.severity))",message="spec.forProvider.severity is a required parameter"
	Spec   AlertSpec   `json:"spec"`
	Status AlertStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AlertList contains a list of Alerts
type AlertList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Alert `json:"items"`
}

// Repository type metadata.
var (
	Alert_Kind             = "Alert"
	Alert_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Alert_Kind}.String()
	Alert_KindAPIVersion   = Alert_Kind + "." + CRDGroupVersion.String()
	Alert_GroupVersionKind = CRDGroupVersion.WithKind(Alert_Kind)
)

func init() {
	SchemeBuilder.Register(&Alert{}, &AlertList{})
}
