// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DashboardInitParameters struct {

	// (Boolean)
	CollapsableRowsMigrated *bool `json:"collapsableRowsMigrated,omitempty" tf:"collapsable_rows_migrated,omitempty"`

	// (String) Description of the dashboard.
	// Description of the dashboard.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Layout of the dashboard.
	// Layout of the dashboard.
	Layout *string `json:"layout,omitempty" tf:"layout,omitempty"`

	// (String) Name of the dashboard.
	// Name of the dashboard.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	PanelMap *string `json:"panelMap,omitempty" tf:"panel_map,omitempty"`

	// (String) Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (List of String) Tags of the dashboard.
	// Tags of the dashboard.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Title of the dashboard.
	// Title of the dashboard.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (Boolean)
	UploadedGrafana *bool `json:"uploadedGrafana,omitempty" tf:"uploaded_grafana,omitempty"`

	// (String) Variables for the dashboard.
	// Variables for the dashboard.
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`

	// (String) Version of the dashboard.
	// Version of the dashboard.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// (String) Widgets for the dashboard.
	// Widgets for the dashboard.
	Widgets *string `json:"widgets,omitempty" tf:"widgets,omitempty"`
}

type DashboardObservation struct {

	// (Boolean)
	CollapsableRowsMigrated *bool `json:"collapsableRowsMigrated,omitempty" tf:"collapsable_rows_migrated,omitempty"`

	// (String) Creation time of the dashboard.
	// Creation time of the dashboard.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Creator of the dashboard.
	// Creator of the dashboard.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// (String) Description of the dashboard.
	// Description of the dashboard.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Autogenerated unique ID for the dashboard.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Layout of the dashboard.
	// Layout of the dashboard.
	Layout *string `json:"layout,omitempty" tf:"layout,omitempty"`

	// (String) Name of the dashboard.
	// Name of the dashboard.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	PanelMap *string `json:"panelMap,omitempty" tf:"panel_map,omitempty"`

	// (String) Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (List of String) Tags of the dashboard.
	// Tags of the dashboard.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Title of the dashboard.
	// Title of the dashboard.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (String) Last update time of the dashboard.
	// Last update time of the dashboard.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) Last updater of the dashboard.
	// Last updater of the dashboard.
	UpdatedBy *string `json:"updatedBy,omitempty" tf:"updated_by,omitempty"`

	// (Boolean)
	UploadedGrafana *bool `json:"uploadedGrafana,omitempty" tf:"uploaded_grafana,omitempty"`

	// (String) Variables for the dashboard.
	// Variables for the dashboard.
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`

	// (String) Version of the dashboard.
	// Version of the dashboard.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// (String) Widgets for the dashboard.
	// Widgets for the dashboard.
	Widgets *string `json:"widgets,omitempty" tf:"widgets,omitempty"`
}

type DashboardParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	CollapsableRowsMigrated *bool `json:"collapsableRowsMigrated,omitempty" tf:"collapsable_rows_migrated,omitempty"`

	// (String) Description of the dashboard.
	// Description of the dashboard.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Layout of the dashboard.
	// Layout of the dashboard.
	// +kubebuilder:validation:Optional
	Layout *string `json:"layout,omitempty" tf:"layout,omitempty"`

	// (String) Name of the dashboard.
	// Name of the dashboard.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	PanelMap *string `json:"panelMap,omitempty" tf:"panel_map,omitempty"`

	// (String) Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	// Source of the dashboard. By default, it is <SIGNOZ_ENDPOINT>/dashboard.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (List of String) Tags of the dashboard.
	// Tags of the dashboard.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Title of the dashboard.
	// Title of the dashboard.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	UploadedGrafana *bool `json:"uploadedGrafana,omitempty" tf:"uploaded_grafana,omitempty"`

	// (String) Variables for the dashboard.
	// Variables for the dashboard.
	// +kubebuilder:validation:Optional
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`

	// (String) Version of the dashboard.
	// Version of the dashboard.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// (String) Widgets for the dashboard.
	// Widgets for the dashboard.
	// +kubebuilder:validation:Optional
	Widgets *string `json:"widgets,omitempty" tf:"widgets,omitempty"`
}

// DashboardSpec defines the desired state of Dashboard
type DashboardSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DashboardParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DashboardInitParameters `json:"initProvider,omitempty"`
}

// DashboardStatus defines the observed state of Dashboard.
type DashboardStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DashboardObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Dashboard is the Schema for the Dashboards API. Creates and manages dashboard resources in SigNoz.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,signoz}
type Dashboard struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.collapsableRowsMigrated) || (has(self.initProvider) && has(self.initProvider.collapsableRowsMigrated))",message="spec.forProvider.collapsableRowsMigrated is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.layout) || (has(self.initProvider) && has(self.initProvider.layout))",message="spec.forProvider.layout is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.uploadedGrafana) || (has(self.initProvider) && has(self.initProvider.uploadedGrafana))",message="spec.forProvider.uploadedGrafana is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.variables) || (has(self.initProvider) && has(self.initProvider.variables))",message="spec.forProvider.variables is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.version) || (has(self.initProvider) && has(self.initProvider.version))",message="spec.forProvider.version is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.widgets) || (has(self.initProvider) && has(self.initProvider.widgets))",message="spec.forProvider.widgets is a required parameter"
	Spec   DashboardSpec   `json:"spec"`
	Status DashboardStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DashboardList contains a list of Dashboards
type DashboardList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Dashboard `json:"items"`
}

// Repository type metadata.
var (
	Dashboard_Kind             = "Dashboard"
	Dashboard_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Dashboard_Kind}.String()
	Dashboard_KindAPIVersion   = Dashboard_Kind + "." + CRDGroupVersion.String()
	Dashboard_GroupVersionKind = CRDGroupVersion.WithKind(Dashboard_Kind)
)

func init() {
	SchemeBuilder.Register(&Dashboard{}, &DashboardList{})
}
