apiVersion: notificationchannel.signoz.crossplane.io/v1alpha1
kind: NotificationChannel
metadata:
  annotations:
    meta.upbound.io/example-id: notificationchannel/v1alpha1/notificationchannel
  labels:
    testing.upbound.io/example-name: slack_ops
  name: slack-ops
spec:
  forProvider:
    name: slack-ops-alerts
    slackConfigs:
    - apiUrlSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      channel: '#ops-alerts'
      sendResolved: true
      text: |-
        {{ range .Alerts }}*{{ .Labels.severity }}*: {{ .Annotations.description }}
        {{ end }}
      title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
